import type { HelixLang } from '@/lib/public-prefs'

export const marketingCopy = {
  en: {
    brand: 'Helix AI',
    nav: [
      { id: 'systems', label: 'Systems', href: '/#catalog' },
      { id: 'lead', label: 'Lead Gen', href: '/#lead-generation' },
      { id: 'how', label: 'How it works', href: '/#how' },
      { id: 'pricing', label: 'Pricing', href: '/pricing' },
      { id: 'studio', label: 'Studio', href: '/studio' },
    ],
    signIn: 'Sign in',
    console: 'Console',
    build: 'Build my system',
    eyebrow: 'Lead Gen v2 — enrich websites or find leads by search',
    eyebrowShort: 'Lead Gen v2 is live',
    eyebrowLight: 'Lead Gen v2 — enrich websites or find leads',
    new: 'New',
    heroBefore: 'AI systems that answer, qualify and book — ',
    heroEm: 'in Arabic and English.',
    lightBefore: 'AI that answers, qualifies and books — ',
    lightEm: 'in Arabic',
    lightAfter: ' and English.',
    lead: 'Helix builds and runs WhatsApp & voice receptionists, lead generation and CRM automations on n8n — with a console that shows exactly what every agent did.',
    leadMobile: 'WhatsApp & voice receptionists, lead generation and CRM automations on n8n — with a console that shows what every agent did.',
    leadLight: 'WhatsApp & voice receptionists, lead generation and CRM automations — built on n8n, run from one honest console.',
    watch: 'Watch a live run',
    trial: 'monthly plan',
    trialShort: '7-day trial',
    noCard: 'Book a discovery call',
    noCardShort: 'Book a call',
    langs: 'Gulf Arabic + English',
    langsShort: 'AR + EN',
    plugs: 'Plugs into the tools you already run',
    plugsNote: '· integrations, not endorsements',
    integrates: 'Integrates with',
    notEndorsements: 'not endorsements',
    demoKicker: 'Live demo',
    demoTitle: 'Watch a system run, step by step.',
    demoBody: 'Every webhook, decision and message is logged. Pick a system and replay a scripted run — the same trace your team sees in the console.',
    demoBodyLight: 'Every webhook, decision and message is logged — the same trace your team reviews in the console.',
    catalogKicker: 'Systems catalog',
    catalogTitle: 'Production systems, not chatbots.',
    catalogBody: 'Each system is an n8n workflow + Helix console module. Start with one; add more when it pays for itself.',
    catalogBodyLight: 'Each system is an n8n workflow + a Helix console module. Start with one.',
    core: 'Core',
    preview: 'Preview add-ons',
    all: 'All',
    howKicker: 'How it works',
    howTitle: 'From brief to live system — you see every step.',
    offerKicker: 'Offer packs',
    offerTitle: 'Clear monthly plans.',
    monthlyCaption: 'Monthly plans · AED',
    studioLink: 'Buying a single system? See per-system prices in Studio →',
    perSystem: 'Per-system pricing · USD · one-time setup + monthly',
    plansLink: 'Prefer a bundled monthly plan? See plans in AED →',
    priceNote: 'Prices from the current pricing catalog.',
    trialCta: 'Book a discovery call',
    scope: "Let's scope it",
    testimonial: 'Testimonial slot — publish only real, named client quotes (with permission). Hidden until the first pilot signs off.',
    ctaTitle: "Tell us the workflow. We'll build the system.",
    ctaBody: 'Five-minute brief. You get a scoped plan in English or Arabic.',
    ctaBodyLight: 'Five-minute brief, in English or Arabic.',
    ctaStart: 'Start at helixx.xo.je/build',
    ctaTalk: 'Talk to us on WhatsApp',
    ctaWa: 'WhatsApp us',
    footerLinks: [
      { label: 'Systems', href: '/studio' },
      { label: 'Pricing', href: '/pricing' },
      { label: 'Updates', href: '/updates' },
      { label: 'Privacy', href: '/privacy' },
      { label: 'Terms', href: '/terms' },
    ],
  },
  ar: {
    brand: 'Helix AI',
    nav: [
      { id: 'systems', label: 'الأنظمة', href: '/#catalog' },
      { id: 'lead', label: 'توليد العملاء', href: '/#lead-generation' },
      { id: 'how', label: 'كيف نعمل', href: '/#how' },
      { id: 'pricing', label: 'الأسعار', href: '/pricing' },
      { id: 'studio', label: 'الاستوديو', href: '/studio' },
    ],
    signIn: 'تسجيل الدخول',
    console: 'اللوحة',
    build: 'ابنِ نظامك',
    eyebrow: 'توليد العملاء v2 — أثرِ بيانات المواقع أو ابحث عن عملاء جدد',
    eyebrowShort: 'توليد العملاء v2 متاح',
    eyebrowLight: 'توليد العملاء v2 — أثرِ المواقع أو ابحث عن عملاء',
    new: 'جديد',
    heroBefore: 'أنظمة ذكاء اصطناعي تردّ وتؤهّل وتحجز — ',
    heroEm: 'بالعربي والإنجليزي.',
    lightBefore: 'ذكاء يردّ ويؤهّل ويحجز — ',
    lightEm: 'بالعربي',
    lightAfter: ' والإنجليزي.',
    lead: 'نبني ونشغّل موظفي استقبال على واتساب والهاتف، وتوليد العملاء، وأتمتة إدارة العملاء على n8n — مع لوحة تحكم تُظهر بالضبط ما فعله كل وكيل.',
    leadMobile: 'موظفو استقبال على واتساب والهاتف، وتوليد العملاء، وأتمتة إدارة العملاء على n8n — مع لوحة تُظهر ما فعله كل وكيل.',
    leadLight: 'موظفو استقبال على واتساب والهاتف، وتوليد العملاء، وأتمتة إدارة العملاء — مبنية على n8n وتُدار من لوحة واحدة صادقة.',
    watch: 'شاهد تشغيلاً مباشراً',
    trial: 'تجربة ٧ أيام بلا قيود',
    trialShort: 'تجربة ٧ أيام',
    noCard: 'بدون بطاقة ائتمان',
    noCardShort: 'بدون بطاقة',
    langs: 'عربي خليجي + إنجليزي',
    langsShort: 'عربي + إنجليزي',
    plugs: 'يتكامل مع الأدوات التي تستخدمها',
    plugsNote: '· تكاملات وليست شراكات',
    integrates: 'يتكامل مع',
    notEndorsements: 'وليست شراكات',
    demoKicker: 'عرض مباشر',
    demoTitle: 'شاهد النظام يعمل، خطوة بخطوة.',
    demoBody: 'كل ويب هوك وقرار ورسالة يُسجَّل. اختر نظاماً وأعد تشغيل سيناريو تجريبي — نفس الأثر الذي يراه فريقك في اللوحة.',
    demoBodyLight: 'كل ويب هوك وقرار ورسالة يُسجَّل — نفس الأثر الذي يراجعه فريقك في اللوحة.',
    catalogKicker: 'كتالوج الأنظمة',
    catalogTitle: 'أنظمة إنتاج، لا روبوتات دردشة.',
    catalogBody: 'كل نظام هو مسار n8n مع وحدة في لوحة Helix. ابدأ بواحد، وأضف غيره عندما يدفع تكلفته.',
    catalogBodyLight: 'كل نظام هو مسار n8n مع وحدة في لوحة Helix. ابدأ بواحد.',
    core: 'الأساس',
    preview: 'إضافات للمعاينة',
    all: 'الكل',
    howKicker: 'كيف نعمل',
    howTitle: 'من الموجز إلى نظام يعمل — ترى كل خطوة.',
    offerKicker: 'الباقات',
    offerTitle: 'ابدأ بسبعة أيام بلا قيود.',
    monthlyCaption: 'الباقات الشهرية · درهم',
    studioLink: 'تشتري نظاماً واحداً؟ شاهد أسعار كل نظام في الاستوديو →',
    perSystem: 'تسعير لكل نظام · دولار · إعداد لمرة واحدة + شهري',
    plansLink: 'تفضل باقة شهرية مجمّعة؟ شاهد الباقات بالدرهم →',
    priceNote: 'الأسعار من كتالوج التسعير الحالي.',
    trialCta: 'ابدأ تجربة ٧ أيام',
    scope: 'لنحدد النطاق',
    testimonial: 'خانة الشهادات — ننشر فقط اقتباسات حقيقية بأسماء عملاء وبإذنهم. تبقى مخفية حتى يوافق أول عميل تجريبي.',
    ctaTitle: 'صف لنا مسار العمل. نبني النظام.',
    ctaBody: 'موجز من خمس دقائق. تحصل على خطة محددة بالعربي أو الإنجليزي.',
    ctaBodyLight: 'موجز من خمس دقائق، بالعربي أو الإنجليزي.',
    ctaStart: 'ابدأ من helixx.xo.je/build',
    ctaTalk: 'كلّمنا على واتساب',
    ctaWa: 'واتساب',
    footerLinks: [
      { label: 'الأنظمة', href: '/studio' },
      { label: 'الأسعار', href: '/pricing' },
      { label: 'التحديثات', href: '/updates' },
      { label: 'الخصوصية', href: '/privacy' },
      { label: 'الشروط', href: '/terms' },
    ],
  },
} as const

export type MarketingCopy = (typeof marketingCopy)[HelixLang]

export const INTEGRATIONS = [
  'n8n',
  'WhatsApp Cloud API',
  'Cal.com',
  'Google Calendar',
  'Supabase',
  'Vapi',
  'HubSpot',
  'Google Sheets',
  'Meta Ads',
  'Tap',
  'Moyasar',
  'Paymob',
]
