import type { HelixLang } from '@/lib/public-prefs'

const en = {
  brand: 'Helix AI',
  kicker: 'Operations console',
  headline: 'The console that tells you exactly what happened.',
  points: [
    'WhatsApp and voice, in Gulf Arabic and English.',
    'Every action is logged for your team to review.',
    '7-day unrestricted trial. No credit card.',
  ],
  sample: 'Sample',
  sampleTitle: 'WhatsApp · missed call',
  sampleMeta: 'Example reply · 4.2s',
  bubbleOut: 'مرحباً! لاحظنا اتصالك. كيف نقدر نساعدك؟',
  bubbleIn: 'أبغى موعد بكرة العصر',
  backHome: 'Back to home',
  signInTitle: 'Sign in',
  signInLead: 'Open the workspace your team already runs.',
  workspace: 'Workspace',
  agency: 'Agency console',
  agencyHint: 'Agency administrators',
  client: 'Client portal',
  clientHint: 'Client users and staff',
  email: 'Work email',
  emailPh: 'jane@company.com',
  password: 'Password',
  forgot: 'Forgot password?',
  show: 'Show password',
  hide: 'Hide password',
  open: 'Open workspace',
  verifying: 'Verifying credentials…',
  noAccount: 'Don’t have an account?',
  trial: 'Start 7-day free trial',
  verifyFailed: 'That confirmation link could not be verified. Request a new one, or sign in if you already have access.',
  switchAgency: 'Switch to Agency console',
  switchClient: 'Switch to Client portal',
  signupTitle: 'Create your workspace',
  signupLead: '7-day unrestricted access. No credit card required.',
  fullName: 'Full name',
  namePh: 'Jane Doe',
  company: 'Company or agency name',
  companyPh: 'Acme Operations',
  confirm: 'Confirm password',
  minChars: 'At least 8 characters.',
  termsBefore: 'I accept the',
  terms: 'Terms of Service',
  and: 'and acknowledge the',
  privacy: 'Privacy Policy',
  start: 'Start 7-day free trial',
  creating: 'Creating workspace…',
  checkTitle: 'Check your email',
  checkBody: 'We sent a verification link to',
  checkRest: 'Open it to activate the 7-day trial and launch your workspace.',
  goSignIn: 'Go to sign in',
  haveAccount: 'Already have an account?',
  signInLink: 'Sign in',
  resetTitle: 'Reset your password',
  resetLead: 'We’ll email a reset link if this address belongs to a workspace.',
  send: 'Send reset link',
  sending: 'Sending reset link…',
  inboxTitle: 'Check your inbox',
  inboxBody: 'If that address is associated with a workspace, an access link has been sent. The link expires in 1 hour.',
  returnSignIn: 'Return to sign in',
  backSignIn: 'Back to sign in',
  setTitle: 'Set a new password',
  setLead: 'Use at least 8 characters.',
  newPassword: 'New password',
  confirmNew: 'Confirm new password',
  update: 'Update password',
  updating: 'Updating password…',
  updatedTitle: 'Password updated',
  updatedBody: 'Your new password is active. Sign in to your workspace.',
  signInWorkspace: 'Sign in to workspace',
  requestNew: 'Request a new recovery link',
  modalTitle: 'Reset your password',
  modalLead: 'We’ll email a reset link if this address has an account.',
  cancel: 'Cancel',
  done: 'Done',
  modalSuccess: 'If that address has an account, a reset link is on its way.',
  close: 'Close dialog',
}

const ar: typeof en = {
  brand: 'Helix AI',
  kicker: 'لوحة التشغيل',
  headline: 'اللوحة التي تُظهر لك بالضبط ما حدث.',
  points: [
    'واتساب وصوت، بالخليجية والإنجليزية.',
    'كل إجراء مسجّل ليراجعه فريقك.',
    'تجربة ٧ أيام بلا قيود. بدون بطاقة.',
  ],
  sample: 'مثال',
  sampleTitle: 'واتساب · مكالمة فائتة',
  sampleMeta: 'رد تجريبي · 4.2 ث',
  bubbleOut: 'مرحباً! لاحظنا اتصالك. كيف نقدر نساعدك؟',
  bubbleIn: 'أبغى موعد بكرة العصر',
  backHome: 'العودة للرئيسية',
  signInTitle: 'تسجيل الدخول',
  signInLead: 'افتح مساحة العمل التي يديرها فريقك.',
  workspace: 'مساحة العمل',
  agency: 'لوحة الوكالة',
  agencyHint: 'مديرو الوكالة',
  client: 'بوابة العميل',
  clientHint: 'مستخدمو العميل والفريق',
  email: 'البريد المهني',
  emailPh: 'jane@company.com',
  password: 'كلمة المرور',
  forgot: 'نسيت كلمة المرور؟',
  show: 'إظهار كلمة المرور',
  hide: 'إخفاء كلمة المرور',
  open: 'افتح مساحة العمل',
  verifying: 'جارٍ التحقق…',
  noAccount: 'ليس لديك حساب؟',
  trial: 'ابدأ تجربة ٧ أيام',
  verifyFailed: 'تعذّر التحقق من رابط التأكيد. اطلب رابطاً جديداً، أو سجّل الدخول إن كان لديك وصول.',
  switchAgency: 'التبديل إلى لوحة الوكالة',
  switchClient: 'التبديل إلى بوابة العميل',
  signupTitle: 'أنشئ مساحة العمل',
  signupLead: 'وصول غير مقيّد لسبعة أيام. بدون بطاقة ائتمان.',
  fullName: 'الاسم الكامل',
  namePh: 'Jane Doe',
  company: 'اسم الشركة أو الوكالة',
  companyPh: 'Acme Operations',
  confirm: 'تأكيد كلمة المرور',
  minChars: '٨ أحرف على الأقل.',
  termsBefore: 'أوافق على',
  terms: 'شروط الخدمة',
  and: 'وأقرّ بـ',
  privacy: 'سياسة الخصوصية',
  start: 'ابدأ تجربة ٧ أيام',
  creating: 'جارٍ إنشاء المساحة…',
  checkTitle: 'تحقق من بريدك',
  checkBody: 'أرسلنا رابط التحقق إلى',
  checkRest: 'افتحه لتفعيل التجربة وإطلاق مساحة العمل.',
  goSignIn: 'إلى تسجيل الدخول',
  haveAccount: 'لديك حساب؟',
  signInLink: 'تسجيل الدخول',
  resetTitle: 'إعادة تعيين كلمة المرور',
  resetLead: 'نرسل رابط إعادة التعيين إذا كان هذا العنوان مرتبطاً بمساحة عمل.',
  send: 'أرسل رابط إعادة التعيين',
  sending: 'جارٍ الإرسال…',
  inboxTitle: 'تحقق من صندوق الوارد',
  inboxBody: 'إذا كان العنوان مرتبطاً بمساحة عمل، فقد أُرسل رابط وصول. تنتهي صلاحيته خلال ساعة.',
  returnSignIn: 'العودة لتسجيل الدخول',
  backSignIn: 'رجوع لتسجيل الدخول',
  setTitle: 'عيّن كلمة مرور جديدة',
  setLead: 'ثمانية أحرف على الأقل.',
  newPassword: 'كلمة المرور الجديدة',
  confirmNew: 'تأكيد كلمة المرور الجديدة',
  update: 'تحديث كلمة المرور',
  updating: 'جارٍ التحديث…',
  updatedTitle: 'تم تحديث كلمة المرور',
  updatedBody: 'كلمة المرور الجديدة فعّالة. سجّل الدخول إلى مساحة العمل.',
  signInWorkspace: 'تسجيل الدخول إلى المساحة',
  requestNew: 'اطلب رابط استعادة جديداً',
  modalTitle: 'إعادة تعيين كلمة المرور',
  modalLead: 'نرسل رابط إعادة التعيين إذا كان لهذا العنوان حساب.',
  cancel: 'إلغاء',
  done: 'تم',
  modalSuccess: 'إذا كان لهذا العنوان حساب، فرابط إعادة التعيين في الطريق.',
  close: 'إغلاق',
}

export const authCopy = { en, ar }

export type AuthCopy = (typeof authCopy)[HelixLang]

const AR_ERRORS: Record<string, string> = {
  'Enter the email address for your workspace.': 'أدخل البريد المهني لمساحة العمل.',
  'Enter your password.': 'أدخل كلمة المرور.',
  'That email and password combination did not match. Check with your account manager if you have lost access.':
    'البريد وكلمة المرور غير متطابقين. راجع مدير حسابك إذا فقدت الوصول.',
  'Too many sign-in requests. Please wait before trying again.': 'محاولات كثيرة. انتظر قليلاً ثم أعد المحاولة.',
  'Authentication is temporarily unavailable. Please try again later.': 'المصادقة غير متاحة مؤقتاً. أعد المحاولة لاحقاً.',
  'Authentication is not configured. Add SUPABASE_URL and SUPABASE_ANON_KEY to .env.local and restart the app.':
    'المصادقة غير مهيأة. أضف مفاتيح Supabase إلى البيئة ثم أعد التشغيل.',
  'Workspace access has not been provisioned. Contact your account manager.':
    'لم يُجهَّز الوصول إلى مساحة العمل. تواصل مع مدير حسابك.',
  'Enter your full name.': 'أدخل اسمك الكامل.',
  'Enter your company or agency name.': 'أدخل اسم الشركة أو الوكالة.',
  'Enter a valid work email address.': 'أدخل بريداً مهنياً صالحاً.',
  'Password must contain at least 8 characters.': 'كلمة المرور يجب أن تكون ٨ أحرف على الأقل.',
  'Password must be at least 8 characters long.': 'كلمة المرور يجب أن تكون ٨ أحرف على الأقل.',
  'Passwords do not match.': 'كلمتا المرور غير متطابقتين.',
  'You must accept the Terms of Service to continue.': 'يجب قبول شروط الخدمة للمتابعة.',
  'An account with this email already exists.': 'يوجد حساب بهذا البريد.',
  'Account creation could not be completed. Try again.': 'تعذّر إنشاء الحساب. أعد المحاولة.',
  'Unable to update password. Your reset link may have expired.': 'تعذّر تحديث كلمة المرور. قد يكون الرابط منتهياً.',
  'Authentication service is temporarily unavailable. Try again shortly.': 'خدمة المصادقة غير متاحة مؤقتاً. أعد المحاولة قريباً.',
}

export function localizeAuthError(lang: HelixLang, message?: string) {
  if (!message) return ''
  if (lang === 'en') return message
  return AR_ERRORS[message] ?? message
}
