export const SEARCH_COPY = {
  en: {
    title: 'Search',
    subtitle: 'Search the web and maps for companies, decision makers, and public listings with verified sources.',
    placeholder: 'Search companies, people, or topics...',
    btnSearch: 'Search',
    searching: 'Searching...',
    modeEverything: 'Everything',
    modeBusinesses: 'Businesses',
    modeWeb: 'Web',
    modeSocial: 'Social profiles',
    modeNews: 'News',
    saveAll: 'Save all as leads',
    saveSelected: 'Save selected',
    resultsSummary: '{count} results · {latency}s',
    btnEnrich: 'Enrich',
    btnSave: 'Save',
    btnWatch: 'Watch',
    btnExtractCompanies: 'Extract companies',
    inLeadsBadge: 'Already in your leads',
    emptyTitle: 'Search the web and maps for companies',
    emptySubtitle: 'Results come from the sources shown above. Nothing is saved until you choose Save.',
    noResults: 'Only {count} found. We do not add placeholder rows.',
    searchError: 'Search could not be completed. Retry shortly.'
  },
  ar: {
    title: 'البحث',
    subtitle: 'ابحث في الويب والخرائط عن الشركات وصناع القرار والقوائم العامة بمصادر موثقة.',
    placeholder: 'ابحث عن شركات، أشخاص، أو مواضيع...',
    btnSearch: 'بحث',
    searching: 'جاري البحث...',
    modeEverything: 'الكل',
    modeBusinesses: 'الشركات',
    modeWeb: 'الويب',
    modeSocial: 'حسابات التواصل',
    modeNews: 'الأخبار',
    saveAll: 'حفظ الكل كعملاء محتملين',
    saveSelected: 'حفظ المحدد',
    resultsSummary: '{count} نتائج · {latency} ثانية',
    btnEnrich: 'إثراء',
    btnSave: 'حفظ',
    btnWatch: 'مراقبة',
    btnExtractCompanies: 'استخراج الشركات',
    inLeadsBadge: 'موجود بالفعل في عملائك',
    emptyTitle: 'ابحث في الويب والخرائط عن الشركات',
    emptySubtitle: 'تأتي النتائج من المصادر الموضحة أعلاه. لا يتم حفظ أي شيء حتى تختار حفظ.',
    noResults: 'تم العثور على {count} فقط. لا نضيف صفوفاً وهمية.',
    searchError: 'تعذر إكمال البحث. أعد المحاولة بعد قليل.'
  }
}
