export const LEADGEN_COPY = {
  en: {
    title: 'Lead Generation',
    subtitle: 'Find business leads and enrich company contact details with verified provenance.',
    tabEnrich: 'Enrich a URL',
    tabFind: 'Find leads',
    enrichHelp: 'We check the homepage plus contact and about pages linked from it.',
    enrichPlaceholder: 'Paste websites, one per line (e.g. acme-roofing.sa)',
    findPlaceholder: 'e.g. roofing contractors in Jeddah',
    hunterOptIn: 'Find decision-maker emails with Hunter (uses credits)',
    hunterDisabled: 'Hunter unavailable. Set HUNTER_API_KEY on the server.',
    hunterCapped: 'Hunter credits used up for this month. On-site emails still work.',
    advanced: 'Advanced',
    btnEnrich: 'Enrich',
    btnFind: 'Find leads',
    exportXlsx: 'Export .xlsx',
    exportCsv: 'Export CSV',
    exportFullCsv: 'Full CSV',
    exportJsonl: 'JSONL',
    colCompany: 'Company',
    colWebsite: 'Website',
    colDescription: 'Description',
    colEmail: 'Email',
    colPhone: 'Phone',
    colSocials: 'Socials',
    colCity: 'City',
    colCountry: 'Country',
    colScore: 'Score',
    colSource: 'Source',
    notFound: 'Not found on the site',
    fewerResults: 'Only {n} found. We do not add placeholder rows.',
    showLog: 'Show log',
    hideLog: 'Hide log',
    paused: 'Paused. Open this page to continue processing.'
  },
  ar: {
    title: 'توليد العملاء',
    subtitle: 'ابحث عن عملاء تجاريين وقم بإثراء بيانات الاتصال بمصداقية ومصادر موثقة.',
    tabEnrich: 'إثراء رابط',
    tabFind: 'البحث عن عملاء',
    enrichHelp: 'نفحص الصفحة الرئيسية وصفحات التواصل ومن نحن المرتبطة بها.',
    enrichPlaceholder: 'الصق المواقع، موقع واحد في كل سطر (مثال: acme-roofing.sa)',
    findPlaceholder: 'مثال: شركات مقاولات في جدة',
    hunterOptIn: 'البحث عن بريد صناع القرار عبر Hunter (يستهلك أرصدة)',
    hunterDisabled: 'Hunter غير متاح. أضف HUNTER_API_KEY على الخادم.',
    hunterCapped: 'نفدت أرصدة Hunter لهذا الشهر. ما زالت عناوين البريد من الموقع تعمل.',
    advanced: 'إعدادات متقدمة',
    btnEnrich: 'إثراء',
    btnFind: 'البحث عن عملاء',
    exportXlsx: 'تصدير .xlsx',
    exportCsv: 'تصدير CSV',
    exportFullCsv: 'ملف CSV كامل',
    exportJsonl: 'تصدير JSONL',
    colCompany: 'الشركة',
    colWebsite: 'الموقع',
    colDescription: 'الوصف',
    colEmail: 'البريد',
    colPhone: 'الهاتف',
    colSocials: 'الشبكات الاجتماعية',
    colCity: 'المدينة',
    colCountry: 'الدولة',
    colScore: 'التقييم',
    colSource: 'المصدر',
    notFound: 'غير موجود في الموقع',
    fewerResults: 'تم العثور على {n} فقط. لا نضيف صفوفاً وهمية.',
    showLog: 'عرض السجل',
    hideLog: 'إخفاء السجل',
    paused: 'متوقف مؤقتاً. افتح هذه الصفحة لمتابعة المعالجة.'
  }
}
