import type { LeadGenRecipe } from './types'

export const LEADGEN_RECIPES: LeadGenRecipe[] = [
  {
    id: 'mena-construction-contact',
    label: 'MENA Construction · Contact pages',
    label_ar: 'مقاولات الشرق الأوسط · صفحات التواصل',
    description: 'Crawl contractor and commercial developer websites for verified public contact pages across Gulf, Jordan, and Egypt.',
    mode: 'crawl',
    engine_default: 'stealth',
    adaptive: true,
    max_pages: 80,
    allow: ['.*/(contact|about|اتصل|من-نحن|en/contact).*'],
    deny: ['.*/(login|cart|wp-admin|cdn-cgi).*'],
    link_extractor: {
      allow_domains: [],
      unique: true,
    },
    selectors: {
      company_name: { css: 'h1, .site-title, meta[property="og:site_name"]', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
      address: { css: 'address, .address, .contact-address', adaptive: true },
    },
    extract: {
      company_name: 'string',
      emails: 'string[]',
      phones: 'string[]',
      socials: 'object',
      address: 'string',
      markdown_excerpt: 'string',
    },
    ad_block: true,
    robots_obey: true,
  },
  {
    id: 'clinic-beauty-mena',
    label: 'Clinics & Aesthetics · MENA',
    label_ar: 'العيادات والتجميل · الشرق الأوسط',
    description: 'Crawl medical clinics, dental practices, and aesthetic centers for verified management and reception contact points.',
    mode: 'crawl',
    engine_default: 'stealth',
    adaptive: true,
    max_pages: 60,
    allow: ['.*/(contact|book|branches|doctors|تواصل|حجز|فروعنا).*'],
    deny: ['.*/(portal|patient-login|cart|admin).*'],
    link_extractor: {
      allow_domains: [],
      unique: true,
    },
    selectors: {
      company_name: { css: 'h1, .brand-title, meta[property="og:site_name"]', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
      address: { css: '.location, .clinic-address, address', adaptive: true },
    },
    extract: {
      company_name: 'string',
      emails: 'string[]',
      phones: 'string[]',
      socials: 'object',
      address: 'string',
      markdown_excerpt: 'string',
    },
    ad_block: true,
    robots_obey: true,
  },
  {
    id: 'shopify-brand',
    label: 'Shopify Brand · Products + Contact',
    label_ar: 'علامة شوبيفاي · منتجات وتواصل',
    description: 'Fetch catalog metadata and extract public brand support, wholesale, and partnership contact details.',
    mode: 'shopify',
    engine_default: 'http',
    adaptive: true,
    max_pages: 40,
    allow: ['.*/pages/(contact|about).*', '.*/policies/contact.*'],
    deny: ['.*/checkouts/.*', '.*/account.*'],
    shopify: {
      include_variants: true,
      max_products: 50,
    },
    selectors: {
      company_name: { css: 'meta[property="og:site_name"], .header__heading', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
    },
    extract: {
      company_name: 'string',
      emails: 'string[]',
      phones: 'string[]',
      socials: 'object',
      products_sample: 'object[]',
      markdown_excerpt: 'string',
    },
    ad_block: true,
    robots_obey: true,
  },
  {
    id: 'competitor-pricing-digest',
    label: 'Competitor Pricing Digest',
    label_ar: 'ملخص أسعار المنافسين',
    description: 'Dynamic JS evaluation of SaaS or agency pricing tiers with structured markdown digest generation.',
    mode: 'digest',
    engine_default: 'dynamic',
    adaptive: true,
    max_pages: 30,
    allow: ['.*/(pricing|plans|products|rates|الأسعار|باقات).*'],
    deny: ['.*/(terms|privacy|signin).*'],
    selectors: {
      company_name: { css: 'h1, title, meta[property="og:site_name"]', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
    },
    extract: {
      company_name: 'string',
      markdown_excerpt: 'string',
      emails: 'string[]',
    },
    ad_block: true,
    robots_obey: true,
  },
  {
    id: 'directory-outbound',
    label: 'B2B Directory Outbound',
    label_ar: 'دليل الشركات وتوليد العملاء',
    description: 'Crawl regional trade association listings, follow outward company domains, and isolate executive emails.',
    mode: 'crawl',
    engine_default: 'stealth',
    adaptive: true,
    max_pages: 100,
    allow: ['.*/(company|listing|directory|member|profile)/.*'],
    deny: ['.*/(search|filter|page=\\d+).*'],
    link_extractor: {
      unique: true,
    },
    selectors: {
      company_name: { css: '.company-title, h1, .member-name', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
      address: { css: '.city, .country, address', adaptive: true },
    },
    extract: {
      company_name: 'string',
      emails: 'string[]',
      phones: 'string[]',
      address: 'string',
    },
    ad_block: true,
    robots_obey: true,
  },
  {
    id: 'sitemap-company-crawl',
    label: 'Sitemap Bounded Crawl',
    label_ar: 'زحف خريطة الموقع المقيد',
    description: 'Inspect XML sitemap entries to selectively target contact, executive, and about pages with low network overhead.',
    mode: 'sitemap',
    engine_default: 'http',
    adaptive: true,
    max_pages: 50,
    allow: ['.*/(contact|team|about|leadership).*'],
    deny: ['.*/(tag|category|author|feed).*'],
    selectors: {
      company_name: { css: 'h1, title, meta[property="og:site_name"]', adaptive: true },
      emails: { css: 'a[href^="mailto:"]', attr: 'href', adaptive: true },
      phones: { css: 'a[href^="tel:"]', attr: 'href', adaptive: true },
    },
    extract: {
      company_name: 'string',
      emails: 'string[]',
      phones: 'string[]',
      markdown_excerpt: 'string',
    },
    ad_block: true,
    robots_obey: true,
  },
]

export function getLeadGenRecipe(id: string): LeadGenRecipe | undefined {
  return LEADGEN_RECIPES.find(r => r.id === id)
}
